
project_id = "ezrfatxvtvuyyphkvdod"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["https://127.0.0.1:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[email]
# Configure email templates
templates = { 
  confirmation = """<h2>Welcome to Our Application</h2>
<p>Thank you for signing up. Please confirm your email by clicking the link below:</p>
<p><a href="{{ .ConfirmationURL }}">Confirm Email</a></p>

<div style="margin-top: 20px; padding-top: 15px; border-top: 1px solid #eee;">
  <table cellpadding="0" cellspacing="0" border="0" style="font-family: Arial, sans-serif; color: #333;">
    <tr>
      <td valign="top" style="padding-right: 15px;">
        <img src="https://eleganmentions.com/public/lovable-uploads/b7704d15-73fd-490e-891c-0f6d44db75a7.png" alt="Sabina" width="80" style="border-radius: 5px;">
      </td>
      <td valign="top">
        <p style="margin: 0; font-weight: bold; font-size: 16px;">EM Auctions Team</p>
        <p style="margin: 3px 0; font-size: 14px;">Elegant Mentions</p>
        <p style="margin: 3px 0; font-size: 14px;">
          <a href="mailto:sabina@elegantmentions.com" style="color: #2754C5; text-decoration: none;">sabina@elegantmentions.com</a>
        </p>
        <p style="margin: 3px 0; font-size: 14px;">
          <a href="tel:+13474977079" style="color: #2754C5; text-decoration: none;">+1 347 497 7079</a>
        </p>
        <p style="margin: 3px 0; font-size: 14px;">
          <a href="https://elegantmentions.com" style="color: #2754C5; text-decoration: none;">elegantmentions.com</a>
        </p>
      </td>
    </tr>
  </table>
</div>
""",
  recovery = """<h2>Password Reset Request</h2>
<p>Hello,</p>
<p>Someone has requested a password reset for your account. If this was you, please click on the link below to reset your password:</p>
<p><a href="{{ .SiteURL }}/auth/recovery?token={{ .Token }}" style="background-color: #4CAF50; color: white; padding: 10px 15px; text-align: center; text-decoration: none; display: inline-block; border-radius: 5px;">Reset Your Password</a></p>
<p>If you did not request a password reset, you can safely ignore this email and your password will remain unchanged.</p>
<p>This link will expire in 24 hours.</p>
<p>Thank you,<br>The Support Team</p>

<div style="margin-top: 20px; padding-top: 15px; border-top: 1px solid #eee;">
  <table cellpadding="0" cellspacing="0" border="0" style="font-family: Arial, sans-serif; color: #333;">
    <tr>
      <td valign="top" style="padding-right: 15px;">
        <img src="https://eleganmentions.com/public/lovable-uploads/b7704d15-73fd-490e-891c-0f6d44db75a7.png" alt="Sabina" width="80" style="border-radius: 5px;">
      </td>
      <td valign="top">
        <p style="margin: 0; font-weight: bold; font-size: 16px;">EM Auctions Team</p>
        <p style="margin: 3px 0; font-size: 14px;">Elegant Mentions</p>
        <p style="margin: 3px 0; font-size: 14px;">
          <a href="mailto:sabina@elegantmentions.com" style="color: #2754C5; text-decoration: none;">sabina@elegantmentions.com</a>
        </p>
        <p style="margin: 3px 0; font-size: 14px;">
          <a href="tel:+13474977079" style="color: #2754C5; text-decoration: none;">+1 347 497 7079</a>
        </p>
        <p style="margin: 3px 0; font-size: 14px;">
          <a href="https://elegantmentions.com" style="color: #2754C5; text-decoration: none;">elegantmentions.com</a>
        </p>
      </td>
    </tr>
  </table>
</div>
"""
}

[analytics]
port = 54327
vector_port = 54328
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcloud.json"
