
project_id = "ezrfatxvtvuyyphkvdod"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["https://127.0.0.1:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[email]
# Add custom email templates
template_folder_path = "supabase/email-templates"
# Template for when a user signs up to your app
confirmation_template = """<h2>Welcome to Our Application</h2>
<p>Thank you for signing up. Please confirm your email by clicking the link below:</p>
<p><a href="{{ .ConfirmationURL }}">Confirm Email</a></p>
"""

# Template for when a user requests to reset their password
recovery_template = """<h2>Password Reset Request</h2>
<p>Hello,</p>
<p>Someone has requested a password reset for your account. If this was you, please click on the link below to reset your password:</p>
<p><a href="{{ .RecoveryURL }}" style="background-color: #4CAF50; color: white; padding: 10px 15px; text-align: center; text-decoration: none; display: inline-block; border-radius: 5px;">Reset Your Password</a></p>
<p>If you did not request a password reset, you can safely ignore this email and your password will remain unchanged.</p>
<p>This link will expire in 24 hours.</p>
<p>Thank you,<br>EM Auctions Team</p>
"""

[analytics]
port = 54327
vector_port = 54328
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcloud.json"
