
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezrfatxvtvuyyphkvdod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6cmZhdHh2dHZ1eXlwaGt2ZG9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzOTQyNzMsImV4cCI6MjA1NDk3MDI3M30.BPmvwOmaFpNDZzYpUngTyn3Os2atD0lyjrPu2dFKp34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storageKey: 'supabase.auth.token'
    }
  }
);

// Add debug logging for function invocation
const originalInvoke = supabase.functions.invoke;
supabase.functions.invoke = async function(functionName, options) {
  console.log(`Invoking Supabase function: ${functionName}`, options);
  try {
    const result = await originalInvoke.call(this, functionName, options);
    console.log(`Function ${functionName} result:`, result);
    return result;
  } catch (error) {
    console.error(`Error invoking function ${functionName}:`, error);
    throw error;
  }
};

// Debug auth operation failures
supabase.auth.onAuthStateChange((event, session) => {
  console.log("Auth state change event:", event);
  console.log("Session active:", !!session);
});

// Add error handling for auth operations
const originalResetPasswordForEmail = supabase.auth.resetPasswordForEmail;
supabase.auth.resetPasswordForEmail = async function(email, options) {
  console.log(`Requesting password reset for email: ${email}`, options);
  try {
    const result = await originalResetPasswordForEmail.call(this, email, options);
    console.log(`Password reset request result:`, result);
    return result;
  } catch (error) {
    console.error(`Error requesting password reset:`, error);
    throw error;
  }
};
